# general settings
name: train_BI_DiffSR_DDIM_S50_x2
model_type: BIDiffSRModel
scale: 2
num_gpu: auto
manual_seed: 10
find_unused_parameters: True

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: MultiPairedImageDataset
    dataroot_gt: datasets/DF2K/HR
    dataroot_lq: datasets/DF2K/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    task: SR
    name: Set5
    type: MultiPairedImageDataset
    dataroot_gt: datasets/benchmark/Set5/HR
    dataroot_lq: datasets/benchmark/Set5/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

# network structures
network_g:
  type: BIDiffSRUNet
  in_channel: 6
  out_channel: 3
  inner_channel: 64
  norm_groups: 16
  channel_mults: [1, 2, 4, 8]
  attn_res: []
  res_blocks: 2
  dropout: 0.2
  image_size: 256
  fp_res: [256, 128]
  total_step: 2000
  dynamic_group: 5 # K

# schedule
beta_schedule:
  scheduler_type: DDIM
  schedule: linear
  n_timestep: 2000
  linear_start: !!float 1e-6
  linear_end: !!float 1e-2
  prediction_type: epsilon
  num_inference_steps: 50
  guidance_scale: 7.5
  is_guidance: False

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  # ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [500000]
    gamma: 1

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true

    lpips: # metric name, can be arbitrary
      type: calculate_lpips
      crop_border: 2
      better: lower

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
